AWSClientRuntime/Sources/Protocols/RestXML/RestXMLErrorPayload.swift
gradle.properties

Upgrading smithy to 1.10.0 and updating associated tests
Need to get to 1.11.0, so incrementally updating to 1.10.0 first.

chore: Upgrade smithy to 1.10.0

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryStructDecodeXMLGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/BlobEncodeGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/ListEncodeFormURLGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/MapEncodeFormURLGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/QueryIdempotencyTokenAutoFillGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/StructDecodeWrappedXMLGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/TimestampGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/flattened-map.smithy
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/query-blobs.smithy
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/query-idempotency-token.smithy
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/query-lists.smithy
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/query-maps.smithy
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/query-timestamp.smithy

In order to support `s3UnwrappedXmlOutput` we'll need to pass in the service shape via the metadata to `MemberShapeDecodeXMLGenerator` -- but this is in conflict with how this class works with AWSQuery.  This needs to be updated.
We'll need to refactor this first, and then we can update the code to accommodate `s3UnwrappedXmlOutput`
Corresponding:
https://github.com/awslabs/smithy-swift/pull/334

chore: refactor awsquery to separate decoder class

---

codegen/Package.swift
codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryStructDecodeXMLGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlStructDecodeXMLGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/serde/S3UnwrappedXMLOutputTraitTests.kt
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/restxml/serde/s3unwrappedxmloutput.smithy

https://github.com/awslabs/aws-sdk-swift/issues/184
https://github.com/awslabs/smithy-swift/pull/335
Adding support for S3UnwrappedXmlOutputTrait

feat: support S3UnwrappedXmlOutputTrait

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/PresignableModelIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/model/traits/Presignable.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration

This PR adds a pre-signable trait to specific operations that are pre-signable.  We will eventually use this trait to generate what we need so that customers can create get presigned requests.
One of many PRs that will be made to drive #230 to completion

chore: add presignable model integration

---

TestLambdaSdk/Package.swift
TestLambdaSdk/Sources/TestSdk/main.swift
codegen/sdk-codegen/build.gradle.kts
scripts/generatePackageSwift.swift

This resolves a naming conflict issue Amplify was having with SPM.
no corresponding PR

fix: Prefix build targets in package manifest on a release

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AWSHttpProtocolJson10Customizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AWSHttpProtocolJson11Customizations.kt

See corresponding pr for details:
https://github.com/awslabs/smithy-swift/pull/347

chore: Remove middleware function from HttpProtocolCustomizable

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/httpResponse/AWSEc2QueryHttpResponseBindingErrorGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryHttpResponseBindingErrorGeneratorTests.kt

This fixes a compile issue in EC2. It was not compiling due to an incorrect type being placed in the error binding. Thus producing two compiler errors: 1 that doesnt conform to the protocol and 2. the init was expecting a diff type. This fixes 1/3 of #391 

fix: compiler error in ec2

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/FormURLHttpBindingResolver.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJsonHttpBindingResolver.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlProtocolGenerator.kt

corresponding:
https://github.com/awslabs/smithy-swift/pull/348
Uses the correct content type instead of just the default one

fix: use correct content type

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSSigningMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/AWSSigningMiddlewareTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt

Instead of passing in a AWSconfig, customers now pass in an expiration of type `Int64`:
```
let pollyConfig = try PollyClient.PollyClientConfiguration(region: "us-west-2")
let input = SynthesizeSpeechInput(outputFormat: .mp3, text: "hello john", voiceId: .lucia)
guard let presignedRequest: SdkHttpRequest = input.presign(config: pollyConfig, expiration: 500) else {
exit(1)
}
```
This mirror's the interface that aws-sdk-kotlin exposes for their generic presigner

feat: update interface for presigner to include expiration only

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/polly/PollyGetPresignerIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSSigningMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSXAmzTargetMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/MutateHeadersMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/RetryMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/SynthesizeSpeechInputGETQueryItemMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/UserAgentMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/AWSSigningMiddlewareTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/AWSXAmzTargetMiddlewareTests.kt

Removing MiddlewareRenderableExecutionContext -- instead, we can instantiate each renderable middleware with any extra context that is needed.
corresponding:
https://github.com/awslabs/smithy-swift/pull/357

chore: refactor remove MiddlewareRenderableExecutionContext and update interface

---

codegen/Package.swift
codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/glacier/GlacierAcccountIdDefault.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/GlacierAccountIdMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/GlacierAccountIdMiddlewareTest.kt

This closes #207 
Auto fills Glacier account id on operations that have account id with "-".
Corresponding PR: https://github.com/awslabs/smithy-swift/pull/355

feat: autofill Glacier accountId

---

AWSClientRuntime/Sources/Auth/AWSCredentialsProvider.swift
AWSClientRuntime/Sources/Auth/CredentialsProvider.swift
AWSClientRuntime/Sources/Auth/CredentialsProviderCRTAdapter.swift
AWSClientRuntime/Sources/Middlewares/SigV4Middleware.swift
AWSClientRuntime/Sources/Signing/AWSSigV4Signer.swift
AWSClientRuntime/Tests/Auth/AWSCredentialProviderTests.swift
AWSClientRuntime/Tests/Sigv4/SigV4SigningTests.swift

This PR allows the exposed protocol for a custom credentials provider to be async using a Future instead of a closure.

fix: change credential provider to be async with future

---

AWSClientRuntime/Sources/Protocols/Ec2Query/Ec2QueryError.swift
codegen/Package.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/httpResponse/AWSEc2QueryHttpResponseTraitWithoutPayload.kt

Fixes ec2 protocol codegen tests
- missing an import statement
- force add the body middleware (similiar to what we do for aws query)
- re-enable tests
- add stream parsing logic in awsclient runtime

chore: fix ec2 protocol codegen tests

---

README.md

chore: update readme with generated api reference docs

---

AWSClientRuntime/Sources/Regions/DefaultRegionResolver.swift
AWSClientRuntime/Sources/Regions/ProfileRegionResolver.swift

**Use case 1:**
* assume customer has logging disabled
* no region provider is properly configured, then customers will see:
```
<No output, SDK will be silent>
```
**Use case 2:**
* Assume customer has logging enabled to `debug` level: `SDKLoggingSystem.initialize(logLevel: .debug)`
* No region provider
Result is that customers will see:
```
2021-11-03T14:55:13-0700 debug DefaultRegionProvider : Attempting to resolve region with: EnvironmentRegionProvider
2021-11-03T14:55:13-0700 debug DefaultRegionProvider : Attempting to resolve region with: ProfileRegionProvider
2021-11-03T14:55:13-0700 debug ProfileRegionResolver : No default profile collection was found at the path of ~/.aws/config
2021-11-03T14:55:13-0700 debug DefaultRegionProvider : Attempting to resolve region with: …
```

chore: improve developer experience with region resolver

---

AWSClientRuntime/Sources/Config/Bundle.swift
AWSClientRuntime/Sources/Config/BundleConfiguration.swift
AWSClientRuntime/Sources/Regions/BundleRegionProvider.swift
AWSClientRuntime/Sources/Regions/DefaultRegionResolver.swift

To make use of `BundleRegionProvider` pulling the region from your bundle:
1.  Create an iOS project (or some sort of project which uses a Bundle)
2.  Add `<debug,production>.xcconfig` to each one of your targets (and assign appropriately)
3. So that the values of these variables are available during execution time of the code, you MUST, inside each of your .xcconfig files, define a variable like:
For Debug.xcconfig
```
AWS_REGION=us-west-2
```
For Production.xcconfig
```
AWS_REGION=us-east-1
```
4. In your Info.plist, add a **Key** with `AWS_REGION` of **Type** `String`, with value: `$(AWS_REGION)`.  For example:
```
<key>AWS_REGION</key>
<string>$(AWS_REGION)</string>
```
5.  Attempt to invoke the `BundleRegionProvider`.
By submitting this pull request, I confirm that my contribution is …

feat: region resolver via bundle

---

AWSClientRuntime/Sources/Regions/BundleRegionProvider.swift

The longest current region size I found had 15 characters (`us-isob-east-1`) -- i multiplied this by 2.5 and got 37.5 and rounded up to 38.

chore: update max region size

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/InputTypeGETQueryItemMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/presignable/PresignableGetIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/InputTypeGETQueryItemMiddlewareRenderable.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration

Adding a presigner for S3's Get Object -- kind of quick and dirty in that we aren't supporting a the input type's that are of type `Date` nor `Int` -- added a TODO for this.
Tested with a quick and dirty hello world app:
```
struct MySpecialEndpointResolver: EndpointResolver {
func resolve(serviceId: String, region: String) throws -> AWSEndpoint {
return AWSEndpoint(endpoint: Endpoint(host: "s3.amazonaws.com"))
}
}
func genPresignedUrlForS3GetObject() throws{
let s3Config = try S3Client.S3ClientConfiguration( endpointResolver: MySpecialEndpointResolver(), region: "us-west-2")
let input = GetObjectInput(bucket: "<INSERT YOUR BUCKET>", key: "<key>")
guard let url = input.presignURL(config: s3Config, expiration: 10000) else {
print("exiting")
exit(1)
}
print(url)
}
try …
```

feat: add s3 get object presigner

---

AWSClientRuntime/Sources/Http/LanguageMetadata.swift
AWSClientRuntime/Tests/Http/LanguageMetadataTests.swift

Prior to doing this, we were improperly generating user agent strings because `.map{}` generates an `[String]` rather than `String` -- so, we need this update to properly generate a user agent string.  Also, I added some unit tests.

fix: Language metadata to render extras properly

---

AWSClientRuntime/Sources/AWSClientConfiguration.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSServiceConfig.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/RestJsonProtocolGeneratorTests.kt

Updated the way we determine region such that if a user passes in an explicit region, we do not instantiate the DefaultRegionResolver, and therefore avoid instantiating the IMDSRegionResolver.
```
if let region = region {
self.region = region
self.regionResolver = nil
self.signingRegion = signingRegion ?? region
} else {
let resolvedRegionResolver = regionResolver ?? DefaultRegionResolver()
let region = resolvedRegionResolver.resolveRegion()
self.region = region
self.regionResolver = resolvedRegionResolver
self.signingRegion = signingRegion ?? region
}
```                        

fix: eliminate latency of instantiation of client on iOS with explicit region

---

versionDependencies.plist

chore: bump version dependency of client runtime to 0.1.1

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/DisabledAuth.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration

Manual customization for certain cognito operations that are not reflected in model correctly as having optional auth but are listed in their documentation as such.

fix: cognito operations

---

AWSClientRuntime/Sources/Auth/AWSCredentialsProvider.swift
AWSClientRuntime/Sources/Auth/CredentialsProviderCRTAdapter.swift
AWSClientRuntime/Tests/Middlewares/Sha256TreeHashMiddlewareTests.swift

This prevents a lifetime issue we had from happening with the aws credentials provider when instantiated by itself and doesn't cause the thread to block indefinitely while the crt is unable to clean up and properly shut down.
This closes #506 

fix: lifetime issue with cred provider

---

Package.swift

https://github.com/awslabs/aws-sdk-swift/issues/545
This change pins the underlying AwsCrt and ClientRuntime to the supported version 

fix: AWS Swift SDK can now pin to the version 0.1.3

---

AWSClientRuntime/Sources/Middlewares/EndpointResolverMiddleware.swift
AWSClientRuntime/Tests/Protocols/RestXML/Models/Errors/ComplexXMLNestedErrorData+Codable.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/RestJsonProtocolGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/BlobEncodeGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/ListEncodeFormURLGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/MapEncodeFormURLGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/QueryIdempotencyTokenAutoFillGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/TimestampGeneratorTests.kt

This closes #541 and #524 and fixes an issue where we were not sending an empty json object across the wire for aws json protocols nor were we generating protocol tests correctly to test for it.
Corresponding PR: https://github.com/awslabs/smithy-swift/pull/408

fix: json protocols with HttpBody

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/presignable/PresignableUrlIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration

This adds pre sign urls for s3 put object.
Corresponding PR: https://github.com/awslabs/smithy-swift/pull/411

fix: add pre sign urls for s3 put object

---

versionDependencies.plist

https://github.com/awslabs/aws-sdk-swift/issues/557
Bumps the ClientRuntime version to 0.2.3 to support Swift 5.6
https://github.com/awslabs/smithy-swift/pull/413.

fix: update client runtime version for Swift 5.6 support

---

versionDependencies.plist

https://github.com/awslabs/aws-sdk-swift/issues/582
Updates dependency on Smithy Swift to [0.2.4](https://github.com/awslabs/smithy-swift/releases/tag/0.2.4). Necessary for Swift 5.7 support.

chore: update client runtime version

---

.github/pull_request_template.md
THIRD-PARTY-LICENSES

N/A
THIRD-PARTY-LICENSES is built using an internal tool to organize the attribution for the SDK. Additionally, it also allows to keep track of the dependency versions.
Also update PR template to make when a change is made, THIRD-PARTY-LICENSES is kept up to date.
This file is generated
docs

docs: add THIRD-PARTY-LICENSES file

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
gradle.properties

(https://github.com/awslabs/aws-sdk-swift/pull/597 is failing due to unresolved shape `smithy.api#Unit` which was introduced in https://github.com/awslabs/smithy/pull/980/)
- `JsonName` trait now has no effect in AwsJson1_0 and AwsJson1_1, this change is supported by https://github.com/awslabs/smithy-swift/pull/425

chore: update smithy version to 1.22.0

---

Package.swift

Adds a setup step to install a Java 18 JDK before building the project.  This is a documentation change only.

Add JDK setup step to development instructions

---

README.md
docs/stability.md

Add a stability policy for AWS SDK for Swift releases & add a link to it in the main README doc
No change; docs only

Add stability policy to SDK docs

---

Package.swift

When loading the `Package.swift` file on Xcode 14, the `setupDependencies()` method call at the bottom of `Package.swift` was not getting executed, and the auto-generated libraries were not being created.
I am not certain of the reason; it seems that Xcode 14 stops interpreting `Package.swift` once the `package` global variable has been defined.  In any case, converting `setupDependencies()` from a free function to a method extended upon the `Package` class fixes the problem & still works with Xcode 13 as well.

bug: Fix `Package.swift` on Xcode 14

---

AWSClientRuntime/Package.swift
Package.swift
codegen/Package.swift

https://github.com/awslabs/smithy-swift/pull/437 deletes a duplicate `Package.swift` file that was contained in a subfolder of the main project.  This project was making reference to the now-deleted `Package.swift` to import the `ClientRuntime` library in the following places:
- `Package.swift` located in the project root directory
- `Package.swift` located in the `AWSClientRuntime/` subfolder
- `Package.swift` located in the `codegen/` subfolder
This project now imports `ClientRuntime` using only the `Package.swift` file in the root of the `smithy-swift` project.
No new dependencies were added to this change, but one dependency (`smithy-swift`) is imported differently.

fix: Use smithy-swift package manifest in root of project

---

.github/workflows/continuous-integration.yml

Update CI build images & tools to latest versions.
- Github runner image updated from `macos-11` to `macos-12`.
- Xcode updated from `13.2.1` to `14.0`
- CRT builder updated from `0.9.13` to `0.9.18`

chore: Update CRT builder & macOS/Xcode to latest

---

Package.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/BoxServices.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/BoxServicesTest.kt
gradle.properties

Changed the way we convert all the members of a service to boxed. The way this was done will not work properly with IDLv2 which does no longer relay on the `Box` trait to determine whether or not a member is nullable. This change aligns with the pull request submitted to the swift-sdk [#444](https://github.com/awslabs/smithy-swift/pull/444) that makes the corresponding changes in the SDK itself.

fix: Use the IDLv2 ClientOptional trait instead of Box

---

scripts/generatePackageSwift.swift

N/A
Follow up PR to https://github.com/awslabs/aws-sdk-swift/pull/635.
This change ensures that the dependencies on `aws-crt-swift` and `smithy-swift` are pinned to exact versions by updating the template used to generate the Package manifest during the release process. 
N/A

fix: pin crt and clientruntime versions

---

Package.swift

N/A
The SDK uses the `from` dependency version requirement for `ClientRuntime` and `CRT`.  This means that any consumer Package or application that depends on a specific version of the AWS SDK for Swift will have their transitive dependencies (`ClientRuntime` and `CRT`) updated with any new release. This is not ideal - it can lead to the improvements in those dependencies causing breaking behavioral changes for consumers. 
One such [improvement](https://github.com/awslabs/smithy-swift/pull/442) ended up breaking workarounds we had in place. While these changes are obviously very welcome, they shouldn't be forced on consumers that pin to a specific version of the AWS SDK for Swift.
We looked into fixing this ourselves here https://github.com/aws-amplify/amplify-ios/pull/2397. 
TL;DR …

fix: pin smithy and crt versions in 0.2.6

---

Package.swift

Followup: https://github.com/awslabs/aws-sdk-swift/pull/635 

fix: pin smithy and crt versions in 0.3.0

---

Package.swift
README.md

Fixes https://github.com/awslabs/aws-sdk-swift/issues/644

docs: update Package.swift with updated SPM spec

---

AWSClientRuntime/Sources/Endpoints/AWSEndpointsRequestContext.swift
AWSClientRuntime/Sources/Endpoints/AWSEndpointsResolvedEndpoint.swift
AWSClientRuntime/Sources/Endpoints/AWSEndpointsResolvedEndpointType.swift
AWSClientRuntime/Sources/Endpoints/AWSEndpointsRuleEngine.swift
AWSClientRuntime/Sources/Endpoints/EndpointError.swift
codegen/smithy-aws-swift-codegen/build.gradle.kts
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSClientRuntimeTypes.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSServiceConfig.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointParamsGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointResolverGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointTestGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/OperationEndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/model/AWSClientContextParamsTransformer.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointParamsGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/RestJsonProtocolGeneratorTests.kt
gradle.properties

https://github.com/awslabs/aws-sdk-swift/issues/624
This changes takes https://github.com/awslabs/aws-crt-swift/pull/79 Swift bindings and create wrappers for it in AWS Client Runtime. These wrappers are used in the service code which is codegen.
No new dependencies were added to this change. 

feat: implement DefaultEndpointResolver using CRT

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/model/AWSEndpointTraitTransformer.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/model/AWSHttpTraitTransformer.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointResolverMiddlewareTests.kt

`Bucket` in the HTTP URI is now a `contextParam` hence rules engine takes care of adding the bucket to the URI to either host name or path depending on the bucket location `forceStylePath` configuration. Therefore, SDK must not add the bucket to the URI outside of the rules engine.
```json
"com.amazonaws.s3#GetObject": {
"type": "operation",
"input": {
"target": "com.amazonaws.s3#GetObjectRequest"
},
"output": {
"target": "com.amazonaws.s3#GetObjectOutput"
},
"traits": {
"aws.protocols#httpChecksum": {
"requestValidationModeMember": "ChecksumMode",
"responseAlgorithms": [
"CRC32",
"CRC32C",
"SHA256",
"SHA1"
]
},
"smithy.api#http": {
"method": "GET",
"uri": "/{Bucket}/{Key+}?x-id=GetObject",
"code": 200
}
}
},
```
```json
"com.amazonaws.s3#GetObjectRequest": {
"type": "structure", …
```

fix: prefer EndpointResolver Bucket for S3 in http label, AccountId for S3Control host label

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryFormURLEncodeCustomizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryFormURLEncodeCustomizations.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/BlobEncodeGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/ListEncodeFormURLGeneratorTests.kt

This PR allows empty lists to be serialized for Aws and Ec2 queries. 
This PR is in response to this change https://github.com/awslabs/smithy/pull/1444 in the latest (1.26.1) smithy version
#665 

fix: Allow empty lists to be serialized for Aws queries and Ec2 queries

---

AWSClientRuntime/.swiftlint.yml

Disable two SwiftLint rules for parity across projects.

chore: Swiftlint rules change

---

.github/workflows/lint.yml
AWSClientRuntime/Sources/IMDS/IMDSClient.swift

Use the latest Github macOS runner for linting Swift instead of the third-party Github action previously used.
Github macOS runners already includes latest `SwiftLint` (currently `0.49.1`):
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
This is an interim change, to get access to latest SwiftLint quickly.  In the long term, Swift linting should be moved back to a Linux runner.  This ticket tracks that task: https://github.com/awslabs/aws-sdk-swift/issues/677

chore: Use Github macOS runner for swiftlint

---

.github/workflows/lint.yml

On the Github workflow for linting, remove the filter for base branch, so that PRs to any branch get linted.

chore: Lint all PRs, regardless of base branch

---

AWSClientRuntime/Tests/Sigv4/SigV4SigningTests.swift
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/ListEncodeFormURLGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/TimestampGeneratorTests.kt

#632 
This PR updates the corresponding tests in response to the work performed in https://github.com/awslabs/smithy-swift/pull/454

fix: Timestamp encoding and decoding 

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointResolverMiddlewareTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AWSQueryOperationStackTest.kt
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/awsquery/query-empty-input-output.smithy

Fixes https://github.com/awslabs/aws-sdk-swift/issues/619
With endpoint 2.0, this change was added to make sure there is auth scheme present always which wasn't the right assumption for some operation like GetCallerIdentity. This change removes this restrictions.
Companion PR https://github.com/awslabs/smithy-swift/pull/465

fix: remove guard for auth scheme for operations such as STS GetCallerIdentity to continue execution

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3Expires.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/TestContextGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/S3ExpiresTest.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/serde/S3UnwrappedXMLOutputTraitTests.kt
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/s3-expires.smithy

fixes #200 
This PR adds a customization during codegen, that will convert members to String shape. 
This is restricted to members named "Expires" on "Output" structures in the S3 service.

fix! Converts Expires members in S3 output structures to String shape

---

README.md
gradle.properties

Related to #721 
Pinning to Smithy 1.26.2 because latest (1.26.3) causes protocol test failures, which we will address in a subsequent PR.

fix: Pin smithy to 1.26.2

---

.spi.yml

Fixes #708
Our builds on Swift Package Index (SPI) either fail or timeout, resulting in the appearance that our package isn't compatible with any platform or Swift version.  I discussed how to fix with the SPI maintainers [here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/2161).
This PR adds a `.spi.yml` config file for SPI that does the following:
- By default the builders are attempting to build all service clients in the SDK, resulting in build timeouts.  Specify `AWSSTS` target for all platforms, which is a small, representative service client that should build quickly and provide adequate proof of compatibility.
- Specify Swift version for Linux builds, and utilize SPI's Docker build containers which have `openssl-dev` pre-installed.
I have validated …

fix: remedy Swift Package Index build failures & timeouts

---

codegen/protocol-test-codegen-local/Tests/swift-codegen/WaitersTests/OutputMatcherTests.swift
codegen/protocol-test-codegen-local/model/main.smithy

Adds a generated waiter that uses an AND expression plus number equality & inequality.  Provides test coverage for issues in smithy-swift PRs:
https://github.com/awslabs/smithy-swift/pull/493
https://github.com/awslabs/smithy-swift/pull/494

fix: Add waiters generated test for AND and for number equality & inequality

---

.github/workflows/codegen-build-test.yml
.github/workflows/release.yml

This PR adds a workflow for regenerating all models, building the full sdk (models included) and running tests.
#801 

chore: Adds new workflow for building the full sdk

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/presignable/PresignableUrlIntegration.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt

After the upgrade to CRT 0.5.0+, the type of expiration changed from Int64 to TimeInterval.
Therefore, services that define presign functions (such as S3) fail to build because of the type mistmatch.
IMO it makes sense to update the type exposed in the functions to TimeInterval since TimeInterval is a better way to describe a value that should be in seconds.
#804 

fix!: Updates `expiration` paramater in `presign` functions to `TimeInterval` type.

---

Package.swift
packageDependencies.plist

- Update smithy-swift to 0.10.0
- Update aws-crt-swift to 0.5.3
- Pin versions in generated manifest

chore: Update smithy-swift & aws-crt-swift; pin to latest versions

---

gradle.properties

N/A
Instead of using the version range style `[1.26.4]` for `smithyVersion`, use the exact version style `1.26.4`.

chore: update smithyVersion to use exact version

---

.github/workflows/lint.yml
Sources/Core/AWSClientRuntime/HttpContextBuilder+Extension.swift

Fixes #677
The SwiftLint project now has containerized SwiftLint available for use:
https://github.com/realm/SwiftLint/pkgs/container/swiftlint
Use the latest stable Dockerized SwiftLint version (currently `0.50.3`) to lint this project.

chore: Use containerized swiftlint

---

Package.swift
packageDependencies.plist

#867 
Updates aws-crt-swift from 0.5.7 to 0.5.8, and smithy-swift from 0.10.3 to 0.10.4.
This PR is a hot fix on aws-sdk-swift v0.9.1.

fix: Update smithy-swift and aws-crt-swift for hot fix release

---

Package.swift
packageDependencies.plist

Pulls in fix for https://github.com/awslabs/aws-sdk-swift/issues/867
Fixes an issue that prevents the SDK from building to an iOS device when building on a M series Mac.

fix: Require aws-crt-swift 0.6.1

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/DisabledAuth.kt

This PR updates the list of operations that should have the [@optionalAuth](https://smithy.io/2.0/spec/authentication-traits.html#smithy-api-optionalauth-trait) trait applied as a customization.
#913 

fix: Updates the list of operations in the disabled auth customization

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/PrepareRelease.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Models/ReleaseManifest.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Models/ReleaseNotesBuilder.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Utils/Process+Git.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Utils/Process+Utils.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/PrepareReleaseTests.swift

This PR updates the `prepare-release` command in the cli to generate a release manifest file. 
The release manifest is used to config a release created on github. It includes fields for the name, tag, release notes, and artifacts.
https://github.com/awslabs/aws-sdk-swift/issues/855

feat: Release Automation - Generate release manifest

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Utils/FileManager+Utils.swift

This PR updates the package manifest generator:
- add services as products
- included resources for the AWSClientRuntime tests
- exclude items that start with `.` when retrieving the list of services from the Sources directory as it may include a `.DS_Store` on mac.
https://github.com/awslabs/aws-sdk-swift/issues/939

fix: Updates package manifest generator to also add services as products

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/GeneratePackageManifest.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Models/LazyValueTests.swift

The CLI is failing to compile on Swift 5.5 due to a complex closure type. This fixes the issue by defining an explicit type for the generic.

fix: Adds explicit type for `LazyValue` in CLI

---

IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift
Sources/Core/AWSClientRuntime/Auth/Credentials+CRT.swift
Sources/Core/AWSClientRuntime/Auth/Credentials.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider+CRT.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider+Factory.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/FileBasedConfiguration.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/FileBasedConfigurationKeys.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/Store/FileBasedConfiguratioStore+CRT.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/Store/FileBasedConfigurationStore.swift
Sources/Core/AWSClientRuntime/Regions/ProfileRegionProvider.swift
Sources/Core/AWSClientRuntime/Utils/Cache/FunctionCache.swift
Tests/Core/AWSClientRuntimeTests/EventStream/AWSMessageEncoderStreamTests.swift
Tests/Core/AWSClientRuntimeTests/Sigv4/SigV4SigningTests.swift
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EventStreamTests.kt

This PR is the corresponding aws-sdk-swift PR for https://github.com/awslabs/smithy-swift/pull/545 which forces http2 for bidirectional event streams. 
https://github.com/awslabs/aws-sdk-swift/issues/870

feat: Forces http2 for bidirectional event streams

---

.github/workflows/codegen-build-test.yml
IntegrationTests/Services/AWSKinesisIntegrationTests/KinesisTests.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
scripts/codegen.sh

https://github.com/awslabs/aws-sdk-swift/issues/973
- `awsJson1_0` and `awsJson1_1` now generate marshallers/unmarshallers that don't "fast-fail" with `fatalError()`
- Added `AWSKinesisIntegrationTests` to ensure that Kinesis (and `awsJson`-based streaming more generally) work as intended
Also: Fixes to `Package.swift` generation & usage in the "Codegen, Build & Test" workflow

fix: Fix streaming for AWS Kinesis

---

README.md
docs/development.md
docs/logging.md

#986
- Focus the README file on getting developers to easily integrate the SDK into their package or Xcode project
- Move extra content (related to SDK development, logging, etc.) to individual files in the `docs/` folder
- Link to new README.md file: https://github.com/awslabs/aws-sdk-swift/blob/jbe/improved_readme/README.md

docs: Improve the project's README

---

.github/workflows/codegen-build-test.yml

On the `codegen-build-test` workflow:
- Update the `actions/checkout`, `actions/cache`, and `actions/setup-java` Github actions to the latest versions
- Update the cache action config to latest recommendations for Gradle
- Installs Corretto 17 (latest Corretto LTS version) for its JVM, log its version with the other tools
Once we've used these updated actions a few times, I'll make this update on other GH workflows.

chore: Update Github actions to latest versions, update Java

---

.github/workflows/codegen-build-test-on-comment.yml

Set `GITHUB_HEAD_REF` when running the CRT builder script on a comment-initiated build.
This is where CRT builder looks for the branch to be checked out: https://github.com/awslabs/aws-crt-builder/blob/3aceaee71bd5d9ec5fba5c388f61b5c022a5159e/builder/core/env.py#L129

fix: Set GITHUB_HEAD_REF when running CRT builder script

---

.github/workflows/codegen-build-test-on-comment.yml

Reports status (i.e. pending) immediately after starting a comment-initiated workflow.

fix: Report initial status on comment-generated workflow

---

.github/workflows/codegen-build-test-on-comment.yml

Set status to 'pending' when a comment-initiated job starts.

fix: Set pending status when comment-initiated workflow starts

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/GeneratePackageManifest.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Models/PackageManifestBuilder.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/GeneratePackageManifestTests.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Models/PackageManifestBuilderTests.swift
Package.swift

Adds the `--include-protocol-tests` flag to the `generate-package-manifest` CLI command.
Protocol tests may then be run from the main app instead of from the separate manifest in `codegen/Package.swift`.  This will speed up build times greatly when both protocol tests and unit / integration tests are to be run as well (this happens often.)

feat: Add protocol test option to manifest generator

---

Tests/Core/AWSClientRuntimeTests/Middlewares/Sha256TreeHashMiddlewareTests.swift

https://github.com/awslabs/aws-sdk-swift/issues/1005
Removes expectations from this test, since they cannot be reliably used on asynchronous tests on Linux.  This particular test does not seem to be causing any problems, but I am nevertheless fixing it because it can potentially cause deadlock.
This code executes in deterministic order, so the callback is guaranteed to have been run before the test ends, but I have also used a `completed` flag to verify that the test assertions were actually run.

fix: Remove expectations from tree hash test

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/TestAWSSDK.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Utils/Process+Swift.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/GeneratePackageManifestTests.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/TestAWSSDKTests.swift

The `test-aws-sdk` CLI command uses the `--parallel` option when running `swift test`.  In practice, this option results in drastically slower tests.
To remedy, the `test-aws-sdk` CLI command now omits the `--parallel` option from `swift test`/

fix: Remove --parallel from swift test cmd to improve performance

---

IntegrationTests/Services/AWSS3IntegrationTests/S3StreamTests.swift
IntegrationTests/Services/AWSS3IntegrationTests/S3XCTestCase.swift
IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift
Sources/Core/AWSClientRuntime/Middlewares/Sha256TreeHashMiddleware.swift

#974 
This PR is the companion of https://github.com/awslabs/smithy-swift/pull/553
- Use the async `readToEndAsync()` method where possible
- `Sha256TreeHashMiddleware` no longer uses `CachingStream` to duplicate body content.  Instead, the body is passed on as in-memory data.

feat: Make data streams completely async

---

Sources/Core/AWSClientRuntime/AWSClientConfiguration.swift
Tests/Core/AWSClientRuntimeTests/AWSClientConfigurationTests.swift

#1036 inadvertently broke the `endpoint` field on client configuration.  This PR restores it, and verifies it with a couple tests.

fix: Custom endpoint config field

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Utils/Process+Utils.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Utils/ProcessUtilsTests.swift
sdk.properties

#1046
Currently, when the AWS SDK CLI test runner fails (i.e. `swift test` exits with a nonzero status code), the AWS SDK CLI command exits but with a status code zero for success.
With this change, when the AWS SDK CLI runs a `Process` and the process exits with a nonzero exit code, an `ExitCode` error (defined in the Swift Argument Parser package) is thrown with the abnormal exit code.
A test is added to verify the change works as expected.

fix: Make AWS SDK CLI test runner fail when tests fail

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/PrepareRelease.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Models/ReleaseNotesBuilder.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Utils/Process+Git.swift

#1031
The change in #1049 broke the release notes script by throwing an uncaught error.  This was detected on a Catapult dry run, where the script failed because of a routine issue (a git diff was not clean, which was expected.)
To remedy, the script is modified to catch the expected exit code & handle it appropriately.
(also: issues with unwanted quotation marks and a broken Github diff link were fixed.)

fix: Release note exit codes cause script failure, other release note issues

---

.github/workflows/continuous-integration.yml

Builds & tests Mac & iOS platforms on oldest & newest Xcode, using a single job matrixed to run 4 combinations of OS, Xcode, and platform.
- Eliminates dependence on CRT builder script, and all of the config for that script is removed.
- No need for Github or AWS credentials on this workflow anymore.  AWS credentials may be removed from this repo after merge.
- Allows for easy add of new Apple platforms (TV, watch, etc.) in the future.
Note: Update the required CI checks to reflect the new names after this PR merges.

chore: Upgrade the Mac CI task

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/PrepareRelease.swift

Remove the assets referenced in the release manifest, which is currently just the release manifest itself.

fix: Remove release manifest assets

---

.github/workflows/continuous-integration.yml
Package.swift

Recently CI builds started failing on macOS 11 CI jobs because `xcbeautify` (installed via Homebrew) was updated to not support macOS 11 & Xcode 13.  `xcbeautify` is not published to Homebrew with versioning, so it is difficult to specify an exact `xcbeautify` version to be installed.
The solution is to use `xcpretty` instead of `xcbeautify` to format logs.  `xcpretty` is slower and less recently updated, but comes pre-installed on every Github mac runner.

fix: Switch CI log processor from xcbeautify to xcpretty

---

Package.swift
packageDependencies.plist

Requires the latest stable version of `aws-crt-swift`.

chore: Require aws-crt-swift 0.13.0

---

Sources/Services/AWSKinesis/models/Models.swift
Sources/Services/AWSLexRuntimeV2/models/Models.swift
Sources/Services/AWSSageMakerRuntime/SageMakerRuntimeClient.swift
Sources/Services/AWSSageMakerRuntime/SageMakerRuntimeClientProtocol.swift
Sources/Services/AWSSageMakerRuntime/models/Models.swift
Sources/Services/AWSTranscribeStreaming/models/Models.swift
codegen/sdk-codegen/aws-models/sagemaker-runtime.2017-05-13.json
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/httpResponse/AWSEc2QueryHttpResponseTraitWithoutPayload.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlProtocolGenerator.kt

#1100
Fixes serializers / deserializers for errors that are embedded in event streams, by accounting for the custom error properties being namespaced under `properties`.
To show the effect of this change clearly, the model for `SageMaker` with the breaking change is included, and code has been regenerated for all AWS services.

fix: Correct serde for errors in event streams

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProviders/ECSCredentialsProvider.swift

Previously merged CR contained a bug where changes to Package.swift were overwritten. Changes should've been made to the related codegen in AWSSDKSwiftCLI. There were also 2 swiftlint warnings that are also taken care of here.
N/A
Previous PR: #1091 
- apply Package.swift changes from aforementioned PR to codegen
- adjust spacing on line to ensure it is less than 125 characters
- switch empty assignment `let _ = x` to preferred `x != nil`

fix: Package.swift changes need to be codegen + swiftlint

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
Package.swift
codegen/Package.swift
codegen/protocol-test-codegen-local/build.gradle.kts
codegen/protocol-test-codegen-local/model/aws-query-extras.smithy
scripts/protogen.sh

#1121
Adds a local protocol test suite for the `awsQuery` protocol, to retest the changes in https://github.com/smithy-lang/smithy-swift/pull/590.
Tests that `awsQuery` can successfully serialize a timestamp into a URL-encoded form.

fix: Add local protocol tests for awsQuery protocol, test timestamp fix

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AWSJsonHttpResponseBindingErrorGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/httpResponse/AWSEc2QueryHttpResponseBindingErrorGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restjson/AWSRestJson1HttpResponseBindingErrorGeneratable.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/AWSRestXMLHttpResponseBindingErrorGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AWSJsonHttpResponseBindingErrorGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsrestjson/AWSRestJson1HttpResponseBindingErrorGeneratableTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/Route53InvalidBatchErrorIntegrationTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryHttpResponseBindingErrorGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/AWSRestXMLHttpResponseBindingErrorGeneratorTests.kt

#1155
Makes the per-operation static factory method `makeError(httpResponse:decoder:)` internal instead of `public` to reduce public API surface area.

fix!: Make error factory methods nonpublic

---

Sources/Core/AWSClientRuntime/HttpContextBuilder+Extension.swift
Sources/Core/AWSClientRuntime/Middlewares/SigV4Middleware.swift
Sources/Core/AWSClientRuntime/Signing/AWSSigV4Signer.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointResolverMiddlewareTests.kt

Milestone ticket: https://github.com/awslabs/aws-sdk-swift/issues/1143
Corresponding PR in `smithy-swift`: https://github.com/smithy-lang/smithy-swift/pull/598
Make pre-existing `AWSSigV4Signer` conform to new `Signer` protocol added to `smithy-swift` in corresponding PR.
Change is required to allow dynamic dispatching of `sign` method based on which concrete implementation of `Signer` is fetched from resolved auth scheme in SRA identity & auth flow.
Refactor `HttpContext` extension following same pattern as in the corresponding PR in `smithy-swift`.

feat: Move over signing flow from SigV4Middleware into AWSSigV4Signer

---

codegen/sdk-codegen/scripts/updatemodels.sh

#1184
Delete all models before copying latest models into the SDK project.
This ensures that models deleted in the latest published set of models will be deleted in the Swift SDK as well. 

chore: Remove all models before copying in latest versions

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Models/PackageManifestBuilder.swift
Package.swift

Add a newline character at the end of `Package.swift`, as is convention for Swift source files, and so as to prevent editors from auto-adding it themselves.

chore: End the SDK package manifest with a newline

---

Package.swift
packageDependencies.plist

https://github.com/aws-amplify/amplify-swift/issues/3324
Update aws-crt-swift to 0.17.0 to fix an issue with App Store submission.
smithy-swift 0.30.1 (which also requires aws-crt-swift 0.17.0) is required as well.
This PR will be used to create aws-sdk-swift patch release 0.26.1

fix: Require aws-crt-swift 0.17.0

---

Package.swift
packageDependencies.plist

https://github.com/awslabs/aws-sdk-swift/issues/1204
Update `aws-crt-swift` dependency to 0.17.0. 

fix: Update aws-crt-swift dependency to 0.17.0.

---

IntegrationTests/Services/AWSS3IntegrationTests/SSOCredentialsProviderTests.swift

- The SSO credential provider test can crash on failure, due to accessing the first element of an empty array.  A check is added to prevent this and allow the test to fail and the rest of the test suite to proceed.
- A `Resources` folder is added to the SQS integration test folder to prevent a build warning.

fix: Integration test crashes on failure, build warning

---

.github/workflows/codegen-build-test-on-comment.yml

Uses the correct ref to check out `smithy-swift` to match the branch used for the SDK.

fix: Fix ref used for smithy-swift checkout in codegen-build-test-on-comment

---

.github/workflows/continuous-integration.yml
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
Package.swift
Tests/Core/AWSClientRuntimeTests/UserAgent/AWSUserAgentMetadataTests.swift

#376
Adds a Xcode 14 / tvOS 16 and a Xcode 15 / tvOS 17 job to SDK continuous integration.
- `xcodebuild` is used to target the tvOS simulator on 2 new CI jobs
- Set minimum tvOS version of 13.0 and minimum watchOS version to 6.0, to match CRT minimums

chore: Run tvOS old & new in CI

---

scripts/ci_steps/prepare_protocol_and_unit_tests.sh

Uses the new manifest generator options to run unit & protocol tests rather than deleting services.

fix: Use new manifest generator options to run protocol & unit tests in CI

---

.github/workflows/codegen-build-test.yml

#1264
- Trigger the codegen-build-test workflow on `pull_request`
- Use the `Codegen-Build-Test` deployment environment for the `codegen-build-test` workflow.
Reference for Github Action environments: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment
The deployment environment is configured to require manual permissions from any member of our Github team to run.

feat: Add codegen-build-test workflow to pull requests

---

.github/workflows/codegen-build-test.yml

Ensures that a matching branch name in `smithy-swift` is used when starting `codegen-build-test` using workflow dispatch.

fix: Fall back to GITHUB_REF_NAME when building on workflow dispatch

---

.github/workflows/generate-documentation.yml
scripts/generatedocc.sh

#1251
- Alphabetically sort the list of services to have docs generated, to ensure the list is deterministic across all docs runners and all service docs get built
- Assume role for the public Cloudfront distro, and perform an invalidation after updating docs

fix: Batch documentation modules properly

---

Sources/Core/AWSClientRuntime/Endpoints/PartitionDefinition.swift

fix: update partitions to latest fixes failing endpoints tests

---

.github/workflows/codegen-build-test.yml
.github/workflows/continuous-integration.yml

- Use macOS 12 / Xcode 14.0.1 / iOS 16.0 / tvOS 16.0 as "earliest" versions on CI.
- Use macOS 13 / Xcode 15.1 / iOS 17.2 / tvOS 17.2 as "latest" versions on CI.

chore: Use Xcode 15.1 as CI latest version

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt

#1196 
After investigation, reached conclusion that the mentioned TODO item isn't referring to renaming the _value_ of the variable but rather the _name_ of the variable itself. The value of the variable _is_ supposed to be fixed at `"application/x-www-form-urlencoded"` and no change is needed. TODO item is likely referring to renaming `defaultContentType` variable to something like `defaultRequestContentType` to erase possible confusion arising from different default content types of response and request of AWS query protocol (response content type is `text/xml`).
Confirmed that the SDK works correctly currently, using STS::GetCallerIdentity which uses AWS query protocol. The returned content type is `text/xml` as expected and response is correctly deserialized.
System works correctly …

Delete unnecessary TODO item.

---

IntegrationTests/Services/AWSS3IntegrationTests/S3ErrorIn200Test.swift

Fixes integration test that fails to compile due to recent change from HttpClientEngine -> HTTPClient and execute -> send. Tested locally

fix: integration tests to conform to latest HTTPClient change

---

.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml
IntegrationTests/Services/AWSECSIntegrationTests/ECSCredentialsProviderTests.swift
IntegrationTests/Services/AWSS3IntegrationTests/ProcessCredentialsProviderTests.swift
IntegrationTests/Services/AWSS3IntegrationTests/S3URLEncodingTests.swift
IntegrationTests/Services/AWSS3IntegrationTests/S3XCTestCase.swift
IntegrationTests/Services/AWSS3IntegrationTests/SSOCredentialsProviderTests.swift
scripts/ci_steps/prepare_integration_tests.sh
scripts/integration-test-sdk.properties

#769
Adds a Github CI workflow that runs integration tests on Mac & Linux.  Tests are run against a dedicated AWS account to be used solely for integration testing.
The general workflow for integration tests:
- Get AWS credentials for the integration test account.
- Code-generate only the services needed for integration tests.
- Build the integration tests.
- Run the integration tests.
Tests run on:
- macOS 12 + Xcode 14.0.1 (Swift 5.7)
- macOS 13 + Xcode 15.2 (Swift 5.9)
- Ubuntu Focal + Swift 5.7
- Ubuntu Focal + Swift 5.9
(AL2 is not enabled because of incompatibility between the AWS credentials GH action and AL2):
https://github.com/aws-actions/configure-aws-credentials/issues/862#issuecomment-1901732082
The three credential provider integration tests are disabled, because they will …

feat: Add integration tests to CI

---

Package.swift
packageDependencies.plist

#1334
Updates aws-crt-swift to 0.26.0. This version of aws-crt-swift removes the swift-collections dependency to avoid a build failure.

chore: Update aws-crt-swift to 0.26.0

---

.github/workflows/codegen-build-test.yml
scripts/ci_steps/log_tool_versions.sh

#1337
Uses a M1-based Github action runner (`macos-14-xlarge`) instead of the standard Intel Mac runner for faster codegen-build-test runs.
Testing shows that this runner takes less than half the time that the standard Intel Mac runner does for this job.
(At some point in the future, this runner may be moved over to Pro-level Apple Silicon.)
Also:
- Use Xcode 15.2, the current latest version.
- Log Mac CPU info along with tools versions.
- Fix formatting in log-tools-versions script.

chore: Use Apple Silicon for codegen-build-test on CI

---

.github/workflows/continuous-integration.yml

#1339
Moves the CI workflow to use M1 Mac instead of Intel Mac for substantially faster builds.
- "Oldest" build moves from Intel Mac / macOS 12 / Xcode 14.0.1 to M1 Mac / macOS 13 / Xcode 14.1
- "Newest" build moves from Intel Mac / macOS 13 / Xcode 15.1 to M1 Mac / macOS 14 / Xcode 15.2
- "Oldest" simulators adjusted to match Xcode versions.
Also:
- Some actions updated to newer major versions.

chore: Update CI to run on Apple Silicon

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
IntegrationTests/Services/AWSSTSIntegrationTests/STSWebIdentityCredentialsProviderTests.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProviders/STSWebIdentityCredentialsProvider.swift
scripts/integration-test-sdk.properties

https://github.com/awslabs/aws-sdk-swift/issues/1189
- Updates the SDK wrapper for STS web identity credentials provider following CRT changes here: https://github.com/awslabs/aws-crt-swift/pull/199/files
- Add the integration test for STS web identity credentials provider that uses STS, IAM, and Cognito.
1. Create a temporary role with assume role policy that accepts unauthenticated OIDC tokens made by Cognito
2. Create a Cognito identity pool, then fetch Cognito ID from it, then fetch OIDC token from it using Cognito ID
3. Save the fetched OIDC token to a file
4. Construct STS web identity credentials provider using the role and the file path to cached token
5. Call `STS::getCallerIdentity` using a STS client that has just the STS web identity credentials provider configured
6. Confirm …

feat: Update STS web identity credentials provider & add integration test

---

IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift

AWS Transcribe changed the way spoken letters are transcribed.  This changes expected text to match what is returned by the service.

fix: Change Transcribe integration test to match service transcription

---

.github/workflows/integration-test.yml

#1353
Changes CI runners from Intel Mac to M1 Mac, and adjusts Xcode/macOS to match those used for continuous integration testing.
Also: provide a `Resources/` folder in STS integration tests to prevent a build warning.

Move integration tests to M1 CI runners, use xcodebuild to test

---

Sources/Services/AWSS3/models/Models.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3ErrorIntegration.kt

This PR addresses an issue introduced in v0.35 and continued in v0.36 that causes some errors to not be thrown properly, such as a 404 from S3.
- instead of creating `RestXMLError` directly, use the `makeError` function which first checks if we should throw a `NotFound` error
Code used to test:
```
let client = try S3Client(region: "us-west-2")
let response = try await client.headObject(input: .init(bucket: "dayaffe-testing", key: "bleh"))
print(response)
```
returns
```
Error: NotFound(httpResponse: 
Status Code: http_status_404 
Content-Type: application/xml, 
Server: AmazonS3, 
x-amz-request-id: SRP9G2CKW75G91GW, 
x-amz-id-2: BEBKkEatJTzJHXmy0RUf+oZon7J2TH2hf4d3NFM5EyQlCeYhduFhQn8vyXVadgy/fjfJz9wnaBY=, 
Date: Wed, 21 Feb 2024 20:27:11 GMT, message: Optional("404 Not Found"), requestID: …
```

fix: should use makeError() to create a RestXMLError

---

IntegrationTests/Services/AWSS3IntegrationTests/S3SigV4ATests.swift

https://github.com/awslabs/aws-sdk-swift/issues/1371

chore: Improve AWSS3 SigV4A integration tests to use preexisting MRAP if applicable.

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointResolverMiddlewareTests.kt

- Add codegen for overwriting signing property value for `signingName` and `signingRegion` if auth scheme is resolved from the resolved endpoint and it has custom values for these.
- Update a codegen test

fix: Add overwrite behavior for endpoints 2.0 for signing properties

---

IntegrationTests/Services/AWSCloudFrontKeyValueStoreIntegrationTests/CloudFrontKeyValueStoreSigV4ATests.swift
IntegrationTests/Services/AWSMediaConvertIntegrationTests/AWSMediaConvertTests.swift

- The MediaConvert service no longer requires endpoint discovery; the regional endpoint accepts requests directly.  Code to request a MediaConvert endpoint is removed.
- The time delay while waiting for a CloudFront KVS to provision is reduced from 20 to 2.5 seconds, to avoid unneeded wait during test runs.

chore: Improve two integration tests

---

.github/workflows/integration-test.yml

#1409
Removes the deploy environment when running integration tests.
The environment has no benefit & is unused.

chore: Remove Github environment for integration tests

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/plugins/AuthSchemePlugin.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/plugins/DefaultAWSAuthSchemePlugin.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/plugins/EndpointPlugin.kt

Plugin code references config objects as `var` in several places without modifying the value, resulting in compile warnings.
This PR changes these references to `let` to avoid the warning.

fix: Change config variables to let to avoid warning

---

Docker/5.10.0/amazonlinux/2/Dockerfile
Docker/5.10.0/ubuntu/22.04/Dockerfile

Adds Dockerfiles for Amazon Linux 2 & Ubuntu 22.04 LTS for using Swift 5.10 with the automated build system.
These Dockerfiles build without error, but have not yet been tested.

chore: Add Dockerfiles for Swift 5.10

---

.github/workflows/codegen-build-test.yml
.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml
.github/workflows/release-configuration-build.yml

- Use Xcode 15.3 as the "latest" version when performing CI builds.
- Use Ubuntu Jammy instead of Focal for all Ubuntu builds.

chore: Use Xcode 15.3 as 'latest' on CI

---

IntegrationTests/Services/AWSS3IntegrationTests/S3EmptyBody404Tests.swift

#1376
Adds an integration test to verify that a HTTP 404 error with an empty response body is thrown as a `NotFound` service error.
This test verifies the correct operation of a service customization already in place.
When the customization is removed, this test fails.

chore: Add integration test for AWS S3 404 with empty response

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/PrepareRelease.swift

https://github.com/awslabs/aws-sdk-swift/issues/1060
- If a repo (smithy-swift or aws-sdk-swift) has had no new commit since the last release, the build system does not create the release-manifest.json file which is an expected artifact. And this missing artifact causes the build system to fail.
- Create the expected file even when there's no change detected, but make it empty to make consumers of the file be no-op. Confirmed with build system owners that this will result in no-op by consumers of the file.

chore: Fix release system bug

---

Sources/Services/AWSS3/models/Models.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3Expires.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/S3ExpiresTest.kt

GH issue: https://github.com/awslabs/aws-sdk-swift/issues/1400
SEP: `--/seps/accepted/shared/s3-expires-shape-customization.md`
- Resulting codegen change in S3 model is included in PR for quick reference.
- Expand pre-existing model preprocessing where `Expires` member shape gets changed from targeting timestamp to string shape if it were nested under output shapes, to change it regardless of where it is.
- This change future-proofs our SDK for this particular SEP. Regardless of whether Smithy team makes the change to the C2J tool to remove the reshaping logic before we GA or not, our SDK's behavior will stay the same (treat Expires as string).

feat!: Make Expires member in S3 always be a String

---

Package.swift
packageDependencies.plist

https://github.com/awslabs/aws-sdk-swift/issues/1457
https://github.com/awslabs/aws-sdk-swift/issues/1467
Require new smithy-swift version `0.41.1`, which includes fixes to the `URLSessionHTTPClient` that were hotfixed onto smithy-swift `0.41.0`.
This PR merges to release candidate branch `jbe/0_36_2_rc`.  After this PR merges, the RC branch will be published as AWS SDK for Swift hotfix version `0.36.2`.

chore: Require smithy-swift 0.41.1

---

build.gradle.kts
codegen/smithy-aws-swift-codegen/build.gradle.kts
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
gradle.properties
scripts/ci_steps/log_tool_versions.sh

There were a lot of noisy logs from Gradle / Kotlin, e.g.
```log
java.rmi.ServerError: Error occurred in server thread; nested exception is: 
Could not connect to kotlin daemon. Using fallback strategy.
java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @46805db7)
...
```
This PR should fix all of the noise (at least locally).
See related links:
- https://youtrack.jetbrains.com/issue/KT-47152/Incremental-Compilation-with-Kotlin-compile-daemon-and-JDK-17-fails-with-IllegalAccessException
- https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target
- https://stackoverflow.com/questions/77607619/android-studio-kotlin-inconsistent-jvm-target- …

feat: bump kotlin version to 1.9.24

---

.github/workflows/generate-documentation.yml
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
Package.swift

Removes DocC as a SDK dependency unless the env var `AWS_SWIFT_SDK_ENABLE_DOCC` is set, since it is essentially unused unless documentation is actually being generated.  There is generally not a reason to enable it by default for customers.
`AWS_SWIFT_SDK_ENABLE_DOCC` is set for the "generate documentation" job on Github, where DocC is actually used.

feat: Require Swift DocC only when env var is set

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHTTPProtocolCustomizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpProtocolServiceClient.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/presignable/PresignableUrlIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/ec2query/EC2QueryCustomizations.kt

`ClientProperty` is being removed in https://github.com/smithy-lang/smithy-swift/pull/726.
This PR removes references to `ClientProperty` in AWS-specific types.
Also: some Kotlin code cleanup.

chore: Remove client properties feature

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHTTPBindingProtocolGenerator.kt

`renderStructEncode()` and `renderStructDecode()` methods are moved into `HTTPBindingProtocolGenerator` (in smithy-swift), so they are deleted in the AWS-specific protocol generator subclass.

chore: Move struct encode/decode to HTTPBindingProtocolGenerator

---

Sources/Core/AWSClientRuntime/UserAgent/AdditionalMetadata.swift
Sources/Core/AWSClientRuntime/UserAgent/ExecutionEnvMetadata.swift
Sources/Core/AWSClientRuntime/UserAgent/OSMetadata.swift
Tests/Core/AWSClientRuntimeTests/UserAgent/AWSUserAgentMetadataTests.swift
Tests/Core/AWSClientRuntimeTests/UserAgent/ExecutionEnvMetadataTests.swift
Tests/Core/AWSClientRuntimeTests/UserAgent/OSMetadataTests.swift

https://github.com/awslabs/aws-sdk-swift/issues/874
Using compiler directive, add "simulator" as additional metadata to OS metadata in user agent header if SDK is being used within simulators.
Also, make the `value` of additional metadata optional to follow the SEP.
The change was tested using a simple iOS application & confirming that user agent header header is changed as expected:
```
User-Agent: aws-sdk-swift/1.0 ua/2.0 api/s3#1.0 os/ios#17.4.0 md/simulator lang/swift#5.10 cfg/retry-mode#legacy
```

feat: Add simulator as additional metadata of OS metadata in user agent

---

.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml
AWSSDKSwiftCLI/Package.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
README.md
codegen/protocol-test-codegen-local/build.gradle.kts
codegen/sdk-codegen/build.gradle.kts

https://github.com/awslabs/aws-sdk-swift/issues/1518
- Bump minimum Swift version from 5.7 to 5.9
- Update simulator versions

chore!: Bump Swift minimum version & bump simulators in CI

---

.swiftlint.yml
Sources/Core/AWSClientRuntime/AWSClientConfigDefaultsProvider.swift
Sources/Core/AWSClientRuntime/Endpoints/AWSEndpoint.swift
Sources/Core/AWSClientRuntime/Endpoints/ServiceEndpointMetadata+Extension.swift
Sources/Core/AWSClientRuntime/Middlewares/AWSS3ErrorWith200StatusXMLMiddleware.swift
Sources/Core/AWSClientRuntime/Middlewares/Sha256TreeHashMiddleware.swift
Sources/Core/AWSClientRuntime/Middlewares/UserAgentMiddleware.swift
Sources/Core/AWSClientRuntime/Middlewares/XAmzTargetMiddleware.swift
Sources/Core/AWSClientRuntime/Regions/DefaultRegionResolver.swift
Sources/Core/AWSSDKEventStreamsAuth/AWSSigV4Signer+EventStreams.swift
Sources/Core/AWSSDKEventStreamsAuth/Context+AWSEventStreamsAuth.swift
Sources/Core/AWSSDKEventStreamsAuth/Context+Signing.swift
Sources/Core/AWSSDKHTTPAuth/AWSSigV4Signer.swift
Sources/Core/AWSSDKHTTPAuth/CustomSigningPropertiesSetter.swift
Sources/Core/AWSSDKHTTPAuth/SigV4AAuthScheme.swift

- Swiftlint was not running on any of the new AWS modules.  This is fixed, along with a few lint violations in those files
- New rules are added for sorted & unused imports (duplicate imports is enabled by default.)
Note that Swiftlint will fix the new import rules automatically by running `swiftlint --fix`.

chore: Enabled swiftlint on modules, added import rules

---

IntegrationTests/Services/AWSS3IntegrationTests/S3PresignedURLTests.swift
Package.swift
Sources/Services/AWSPolly/Sources/AWSPolly/Models.swift
Sources/Services/AWSS3/Sources/AWSS3/Models.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/InputTypeGETQueryItemMiddleware.kt

#1222
In completing #1566, it appears that query items in presigned URLs are rendered incorrectly.
This PR corrects the rendering, regenerates the affected operations, and adds presigned URL integration tests to test for future regression.

fix: Correct query items in presigned URLs, add integration tests

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/PrepareRelease.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/PrepareReleaseTests.swift

When preparing a release with SDK CLI tools, don't add the folder `Tests/Services` to Git staged files since it no longer exists.

fix: Don't git add Tests/Services folder since it no longer exists

---

.github/workflows/continuous-integration.yml
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/GeneratePackageManifest.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Models/PackageManifestBuilder.swift
AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
codegen/Package.swift
scripts/ci_steps/prepare_protocol_and_unit_tests.sh
scripts/protogen.sh

https://github.com/awslabs/aws-sdk-swift/issues/1551
In logical order, from top to bottom:
- Add a new `Package.swift` for protocol tests, under codegen/.
- Remove `addProtocolTests()` function from the `Package.Base.swift`.
- Remove `includeProtocolTests` flag and `addProtocolTests()` function call codegen from AWSSDKSwiftCLI package codegen.
- Remove `includeProtocolTests` flag from where they're used in scripts.
- Update GH CI to run protocol tests with the new `Package.swift` under codegen/.

feat!: Standalone protocol test package

---

Package.swift
packageDependencies.plist

https://github.com/awslabs/aws-sdk-swift/issues/696
Update to latest aws-crt-swift (0.32.0) for updates needed for observability.

chore: Use aws-crt-swift 0.32.0

---

.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml
IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift

https://github.com/awslabs/aws-sdk-swift/issues/1608
- Disable the forcing of Github Actions onto Node 20 since AL2 is incompatible with that version of Node.
- The Transcribe Streaming integration test transcription has been changed slightly by the service.  Verification of the transcription is now case-insensitive, and allows for any of the previous variations that the service has returned.

chore: Prevent node 20 from running on AL2, fix transcribe expectation

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHTTPBindingProtocolGenerator.kt

Adapts constructor call to remove the operationMiddleware param from HttpProtocolTestGenerator.

chore: Refactor protocol tests

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
Package.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointTestGenerator.kt

https://github.com/awslabs/aws-sdk-swift/issues/1627
- Use the TestInitializer in SmithyTestUtils to initialize CRT
- Remove CRT as a service client test dependency

chore: Use TestInitializer to initialize CRT

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AWSQueryOperationStackTest.kt

https://github.com/awslabs/aws-sdk-swift/issues/1681
Code changes in https://github.com/smithy-lang/smithy-swift/pull/801 break tests in this project.  This PR fixes those tests.

fix: Supply explicit type on `forEach` block to try preventing compiler crash

---

Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentity.swift
Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentityResolvers/CustomAWSCredentialIdentityResolver.swift
Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentityResolvers/StaticAWSCredentialIdentityResolver.swift

#1691
`AWSSDKIdentity` re-exports the AWS credential-related types in `SmithyIdentity` to simplify the user experience and place all SDK identity providers in one place.

feat: Re-export SmithyIdentity components to hide Smithy dependency

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/AWSSDKSwiftCLI/Subcommands/PrepareRelease.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/PrepareReleaseTests.swift

#1721
Patch version will now automatically increment for aws-sdk-swift on a new release instead of minor version.  Since current version is `0.76.0`, the next version after this change would be `0.76.1`.
Minor versions will continue to increment for smithy-swift.
A change to accommodate manual bumps to minor & major version will follow.

feat: Ship patch versions for aws-sdk-swift

---

Package.swift
Sources/Core/AWSSDKIdentity/Tests/AWSSDKIdentityTests/AWSCredentialIdentityResolverTests/ProcessAWSCredentialIdentityResolverTests.swift
Sources/Core/AWSSDKIdentity/Tests/AWSSDKIdentityTests/AWSCredentialIdentityResolverTests/ProfileAWSCredentialIdentityResolverTests.swift
Sources/Core/AWSSDKIdentity/Tests/AWSSDKIdentityTests/Resources/config_with_process
packageDependencies.plist

https://github.com/awslabs/aws-sdk-swift/issues/1739
Uses aws-crt-swift 0.36.0.
There is a change in profile credential provider behavior: profile credential provider now uses a process for obtaining credentials if one is provided in the profile.  (This has been confirmed with @waahm7 as an intentional change in credential resolution behavior).  Tests have been updated to reflect the new behavior, and profile resolution tests are now provided with and without 

chore: Update to aws-crt-swift 0.36.0

---

IntegrationTests/Services/AWSS3IntegrationTests/S3ConcurrentTests.swift

Reduce concurrent runs of S3 concurrent integration tests from 100x to 20x to try to reduce spurious failures.

chore: Scale concurrent integration tests from 100x to 20x

---

.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml

Github intends to remove Xcode 16 from the `macos-14` CI runner on Oct. 28:
https://github.com/actions/runner-images/issues/10703
Accordingly, we need to move our Xcode 16-based builds onto the `macos-15` CI runner by that date.
Per the reference above, the `macos-13` runner will remain unchanged so no need to change our builds that run there.
This PR updates Xcode 16 builds to use the `macos-15` runner instead of `macos-14`.

chore: Use macOS 15 with Xcode 16 on CI

---

IntegrationTests/Services/AWSS3IntegrationTests/S3ConcurrentTests.swift

Disable S3 concurrent integration tests on Apple platforms since the tests intermittently fail on those platforms.  Investigation of the cause will be handled separately.

chore: Disable S3 concurrent integration tests on Apple platforms

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/DocIndex.Base.md

https://github.com/awslabs/aws-sdk-swift/pull/1792 attempted to remove the "dev preview" notice, but removed it from the generated index only, so that the notice returned when the API doc index was regenerated.
This PR changes the "base" content of the API doc generated index so that the deletion will be applied to all future API doc indexes.

chore: Remove "dev preview" notice from API docs

---

Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/Middlewares/Sha256TreeHashMiddleware.swift
Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/UserAgent/BusinessMetrics.swift
Sources/Core/AWSClientRuntime/Tests/AWSClientRuntimeTests/Middlewares/FlexibleChecksumsMiddlewareTests.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/RulesBasedAuthSchemeResolverGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/OperationEndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/RulesBasedAuthSchemeResolverGeneratorTests.kt

https://github.com/smithy-lang/smithy-swift/pull/853 changes the `Context` type to make it thread-safe.
This PR gets/sets `Context` attributes by accessing the `Context` directly (which now has thread-safe accessors) rather than by accessing the Context's `attributes` property (which has now been made private).

fix: Make Context thread-safe

---

.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml

[Github Runner v2.321.0](https://github.com/actions/runner/releases/tag/v2.321.0) removed Node 16.  Since AL2 is not compatible with Node 20 due to the glibc version it uses, several important Github Actions may no longer run on AL2.
This PR disables CI on AL2.  Linux is still covered by running Ubuntu tests.  It is likely that we will not be able to test Amazon Linux on Github again until Swift adopts a newer version of Amazon Linux, i.e. 2023.

chore: Disable CI on AL2

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/DisabledAuth.kt

2141
- Turns off disabled auth customization from operations that already have empty auth trait in their model

chore: Remove disabled auth customization where it's no longer needed

---

Package.swift
Sources/Core/AWSSDKIdentity/Tests/AWSSDKIdentityTests/AWSCredentialIdentityResolverTests/STSAssumeRoleAWSCredentialIdentityResolverTests.swift
packageDependencies.plist

- New v0.40.0 of aws-crt-swift fixes a bug with the underlying sts assume role credentials provider where initialization would throw error due to missing bootstrap argument. Link to release: https://github.com/awslabs/aws-crt-swift/releases/tag/v0.40.0
- Delete a test case that wrongly depends on this bug behavior.

chore: Bump aws-crt-swift version to 0.40.0

---

AWSSDKSwiftCLI/Sources/AWSCLIUtils/Version.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Utils/VersionUtilsTests.swift

- In CLI tools, trim whitespace before parsing project version, i.e. from the `Package.version` and `Package.version.next` files.
- Test is added to verify whitespace is successfully trimmed.
This will make the tools more forgiving when versions are inadvertently saved with whitespace, i.e. by text editors.

chore: Trim whitespace before parsing Version

---

IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift

The 25x concurrent test intermittently fails on Linux due to an undiagnosed error in the CRT HTTP client.
This PR disables that test on Linux until a fix is ready.

chore: Disable the 25x bidirectional streaming test on Linux

---

Sources/Core/AWSSDKForSwift/Documentation.docc/s3compatible.md

Provides instructions for using AWS SDK for Swift with "S3-like" or "S3-compatible" third party cloud storage services.

chore: Instructions for S3 MD5 checksum fallback

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/awsjson/AWSJSON1_0ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/awsjson/AWSJSON1_1ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/awsquery/AWSQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/ec2query/EC2QueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/restjson/AWSRestJson1ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/protocols/restxml/RestXMLProtocolGenerator.kt

Recently it was discovered that several AWS JSON-based services have input or output members with the `@httpLabel` trait applied, even though the trait has no meaning in AWS JSON.  Currently, AWS SDK for Swift does not serialize/deserialize a member containing `@httpLabel`, resulting in incorrect behavior on 15 AWS JSON services.
To correct:
- A customizable function returning HTTP body members is added to `HTTPBindingProtocolGenerator` in https://github.com/smithy-lang/smithy-swift/pull/907
- All six AWS protocols override that method in this PR to more exactly specify their HTTP body members.

fix: Refine rules for members of HTTP body per-protocol

---

Package.swift
packageDependencies.plist

Upgrade aws-crt-swift to [0.44.0](https://github.com/awslabs/aws-crt-swift/releases/tag/v0.44.0)
This version lifts the upper limit on event stream message size from 16MB to 256MB.

chore: Update to aws-crt-swift 0.44.0

---

sdk.properties

Remove the Elastic Inference service, which is being shut down.

chore: Remove Elastic Inference

---

IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift

Moves transcribe streaming integration tests to `us-east-2` due to problems occurring in `us-west-2` today.

chore: Move transcribe streaming integration tests to us-east-2

---

Package.swift
packageDependencies.plist

Updates `aws-crt-swift` to 0.48.0
- enforces 24MB limit on streamed events

chore: Update to aws-crt-swift 0.48.0

---

.github/workflows/continuous-integration.yml

Runs Github Linux CI tasks on both x86 & ARM architectures.

chore: Run SDK Linux CI tasks on ARM architecture

---

Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/AWSClientConfigDefaultsProvider.swift
Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentityResolvers/DefaultAWSCredentialIdentityResolverChain.swift
Sources/Core/AWSSDKIdentity/Tests/AWSSDKIdentityTests/AWSCredentialIdentityResolverTests/DefaultAWSCredentialIdentityResolverChainTests.swift

Reverts awslabs/aws-sdk-swift#1926
STS assume role credential provider was accidentally removed from the chain. Reverting this back temporarily, will put up a new PR.

Revert "feat: Decompose CRT default chain into individual wrappers"

---

Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/Protocols/AWSJSON/AWSJSONError.swift
Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/Protocols/AWSQuery/AWSQueryCompatibleUtils.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHTTPProtocolCustomizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/swiftmodules/AWSClientRuntimeTypes.kt

Fixes a compile error that occurs when a RPCv2CBOR-based service uses backward query compatibility for errors.
- Moves AWS JSON & CBOR query-compatibility code to a utility type instead of extending the base errors for those protocols.

fix: RPCv2CBOR query compatible support

---

IntegrationTests/Services/AWSKinesisIntegrationTests/KinesisTests.swift
IntegrationTests/Services/AWSS3IntegrationTests/S3EventStreamTests.swift
IntegrationTests/Services/AWSTranscribeStreamingIntegrationTests/TranscribeStreamingTests.swift

Services are permitted to add new event types to existing event streaming operations.  These appear in the Swift SDK as new cases in existing enumerations.
Several of our integration tests are currently constructed in a way such that they will either:
- fail to compile if a new event type is modeled in an existing event stream
- fail at runtime if the service returns an event type that is not currently modeled
There are three event streaming integration tests in the SDK's integration test suite.  All 3 have been fixed here to be tolerant of both types of new events described above.

fix: Make event stream tests tolerant of added event types

---

codegen/protocol-test-codegen-local/Tests/swift-codegen/Tests/WaitersTests/OutputMatcherTests.swift

#1981
Adds test for matching `ALL_STRING_EQUALS` for one string.
This test verifies a bugfix in https://github.com/smithy-lang/smithy-swift/pull/947.

fix: ANY_STRING_EQUALS waiter matcher match on one string

---

IntegrationTests/Services/AWSBedrockRuntimeIntegrationTests/BedrockAPIKeyTests.swift

Disables one integration test to unblock the automated build system.

fix: Disable Bedrock integration test

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSSwiftDependency.kt

Companion to smithy-swift PR https://github.com/smithy-lang/smithy-swift/pull/954.
Removes the `distributionMethod` property from AWS's `SwiftDependency` instances.

chore: Remove package scope property

---

Sources/Services/AWSSMS/Tests/AWSSMSTests/EndpointResolverTest.swift
codegen/sdk-codegen/aws-models/sms.json

Removes 4 endpoint tests from the `sms` service that are not compatible with upcoming changes to AWS partitions.
Includes:
- Manual removal of endpoint test definitions from the `sms` model
- Regenerated Swift endpoint tests after this model change.

chore: Remove 4 endpoint tests from SMS

---

.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml

- All install simulator steps are removed since Github runner images now ship with sims installed for the default macOS version.
- Latest macOS is changed to 26.  The `macos-26` runner is currently in beta, but unlike `macos-15` it ships with all Xcode 26 sims preinstalled & ready.

chore: Run "latest" Mac builds on macOS 26

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/RulesBasedAuthSchemeResolverGeneratorTests.kt

Fixes tests affected by companion smithy-swift PR:
https://github.com/smithy-lang/smithy-swift/pull/976

chore: Eliminate compile warning in generated auth scheme resolvers
