awslabs/aws-sdk-swift

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpProtocolClientGeneratorFactory.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpProtocolCustomizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AWSHttpProtocolJson10Customizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AWSHttpProtocolJson11Customizations.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/apigateway/ApiGatewayAddAcceptHeader.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/glacier/GlacierAddVersionHeader.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3SigningConfig.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSSigningMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSXAmzTargetMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/MutateHeadersMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/RetryMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/UserAgentMiddleware.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt

Corresponding:
https://github.com/awslabs/smithy-swift/pull/338
Refactored code in order to have the capability of modeling what middlewares should be added to individual operations.

chore: refactor operation middleware

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt

remove addDefaultOperationMiddlewares
corresponding:
https://github.com/awslabs/smithy-swift/pull/339

chore: remove addDefaultOperationMiddlewares

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/s3/S3SigningConfig.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSSigningMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSXAmzTargetMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/EndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/MutateHeadersMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/RetryMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/UserAgentMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/AWSSigningMiddlewareTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/AWSXAmzTargetMiddlewareTests.kt

corresponding:
https://github.com/awslabs/smithy-swift/pull/345

chore: unify middleware between client and protocol codegen tests

---

versionDependencies.plist

Updates version of dependencies

chore: update version of the crt and smithy swift

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/polly/PollyGetPresignerIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/polly/PollySynthesizeSpeechGETQueryItemMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/AWSSigningMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/SynthesizeSpeechInputGETQueryItemMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/AWSSigningMiddlewareTests.kt

<DRAFT>
Heading in the right direction, but need to implement a piece of middleware which is able to take the input object and put it into the query string.
Corresponding:
https://github.com/awslabs/smithy-swift/pull/354

feat: Implement GET presigner for synthesizespeech

---

AWSClientRuntime/Tests/Protocols/RestJSON/RestJSONErrorTests.swift
AWSClientRuntime/Tests/Protocols/RestXML/RestXMLErrorTests.swift
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXMLProtocolNoInputNoOutputGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXMLProtocolXMLAttributesGeneratorTests.kt

Corresponding PR: https://github.com/awslabs/smithy-swift/pull/358

fix: unit tests

---

AWSClientRuntime/Sources/Middlewares/SigV4Middleware.swift
AWSClientRuntime/Sources/Signing/AWSSigV4Signer.swift
AWSClientRuntime/Tests/Sigv4/SigV4SigningTests.swift

No corresponding PRs
https://github.com/awslabs/aws-sdk-swift/issues/388
Need the ability to instrument the signer for various URLs

feat: Expose sigv4 signer for SdkHttpRequestBuilder

---

gradle/wrapper/gradle-wrapper.properties

Corresponding:
https://github.com/awslabs/smithy-swift/pull/359

chore: upgrade gradle to 7.2

---

versionDependencies.plist

in preparation for release, update version deps.

chore: update version dependencies

---

.github/workflows/generate-docs.yml
scripts/generateDocs.sh
scripts/generateIndexPage.sh

Once approved, I will kick off a job which generates all the reference documentation

feat: scripts & update CI for generating api reference documentation

---

AWSClientRuntime/Sources/Middlewares/Sha256TreeHashMiddleware.swift
AWSClientRuntime/Tests/Middlewares/Sha256TreeHashMiddlewareTests.swift
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSClientRuntimeTypes.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/glacier/GlacierChecksum.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/Sha256TreeHashMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration

Closes #208 
Corresponding PRs: https://github.com/awslabs/smithy-swift/pull/362 and https://github.com/awslabs/aws-crt-swift/pull/46

feat: Glacier Checksums Customization

---

versionDependencies.plist

in preparation for release, update versions of smithy swift and crt.

chore: update versions of crt and smithy swift

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
gradle.properties

corresponding:
https://github.com/awslabs/smithy-swift/pull/366

chore: upgrade smithy to 1.12.0

---

AWSClientRuntime/Sources/Auth/AWSCredentialsProvider.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderContainerConfig.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderSTSConfig.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderWebIdentityConfig.swift

This closes #275 and #354 and #351

feat: add three new credential providers

---

AWSClientRuntime/Sources/Regions/DefaultRegionResolver.swift
AWSClientRuntime/Sources/Regions/EnvironmentRegionProvider.swift
AWSClientRuntime/Sources/Regions/IMDSRegionProvider.swift
AWSClientRuntime/Sources/Regions/ProfileRegionResolver.swift
AWSClientRuntime/Sources/Regions/RegionProvider.swift
AWSClientRuntime/Sources/Regions/RegionResolver.swift

feat: add ec2 region provider

---

scripts/generateDocs.sh

fix: document generation script path

---

builder.json
codegen/Package.swift
codegen/protocol-test-codegen/build.gradle.kts
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_0_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsjson/AwsJson1_1_ProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt
gradle.properties

Corresponding:
https://github.com/awslabs/smithy-swift/pull/383

chore: upgrade to smithy 1.13.0

---

versionDependencies.plist

Update to use new versions in prep for release

fix: update versions of crt and smithy swift

---

README.md

For copy and paste people, maybe we should add a comment here?

Update readme.md with latest version

---

AWSClientRuntime/Sources/Regions/BundleRegionProvider.swift

Ah! we need to run swift test w/ running with iOS. ~~i'll update CI as part of this commit as well!~~. I'm not finding a good way to specify  the OS with the `swift test` command.

chore: fix return value in BundleRegionProvider

---

gradle.properties

corresponding:
https://github.com/awslabs/smithy-swift/pull/385

chore: upgrade smithy to 1.13.1

---

versionDependencies.plist

chore: update crt and cr to new version

---

AWSClientRuntime/Sources/Auth/AWSCredentialsProvider.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderChainDefaultConfig.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderContainerConfig.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderSTSConfig.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderWebIdentityConfig.swift
AWSClientRuntime/Sources/IMDS/IMDSClient.swift

Corresponding PR: https://github.com/awslabs/smithy-swift/pull/390

fix: changes to fix lifetime issues when multiple sdks are in use

---

versionDependencies.plist

chore: bump version deps to 0.1.0

---

build.gradle.kts
buildSrc/build.gradle.kts
gradle.properties
settings.gradle.kts

corresponding:
https://github.com/awslabs/smithy-swift/pull/392

chore: update build system to remove hardcoded maven urls

---

AWSClientRuntime/Sources/Http/AWSUserAgentMetadata.swift

corresponding:
https://github.com/awslabs/smithy-swift/pull/394

chore: os version in useragent for foundation based OS

---

AWSClientRuntime/Sources/Signing/SigningFlags.swift

Customers need this to control the sigv4 signer

chore: make signing flags public

---

scripts/updateReleaseToLocalDev.sh

chore: add script to facilitate local dev of generated SDK

---

scripts/updateReleaseToLocalDev.sh

chore: update script to remove Package.swift file in subdir

---

scripts/buildswiftsdk.sh

chore: add buildswiftsdk script as a help builder

---

versionDependencies.plist

chore: bump version dependency of smithy-swift

---

versionDependencies.plist

Update versions in prep for release

fix: update versions in prep for release

---

versionDependencies.plist

fix: update version of crt and client runtime in prep for release

---

AWSClientRuntime/Tests/Sigv4/SigV4SigningTests.swift

Corresponding PR: https://github.com/awslabs/smithy-swift/pull/409 & https://github.com/awslabs/aws-crt-swift/pull/61

fix: signing tests

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/route53/StripHostedZoneURLPathMiddleware.kt

Corresponding PR: https://github.com/awslabs/smithy-swift/pull/410

fix: async bug leftover

---

versionDependencies.plist

Update version of the crt and runtime layer in prep for release

fix: update version of the crt and client runtime

---

versionDependencies.plist

Required to support Smithy 1.22.0 which are introduced in https://github.com/awslabs/smithy-swift/pull/425
ClientRuntime: https://github.com/awslabs/smithy-swift/releases/tag/0.2.5

chore: update client runtime version

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/RestJsonProtocolGeneratorTests.kt

https://github.com/awslabs/aws-sdk-swift/issues/576
https://github.com/awslabs/aws-sdk-swift/issues/603
Fix test case expected string which is changed due to https://github.com/awslabs/smithy-swift/pull/429

fix: test case expected result due to https://github.com/awslabs/smithy-swift/pull/429

---

codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/AWSHttpBindingProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointResolverGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointTestGenerator.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/ServiceGeneratorIntegration.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/middleware/OperationEndpointResolverMiddleware.kt
codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/RestXmlProtocolGenerator.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EndpointParamsGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/OperationEndpointResolverMiddlewareTests.kt
codegen/smithy-aws-swift-codegen/src/test/resources/software.amazon.smithy.aws.swift.codegen/endpoints.smithy

Some params were missed and we didn't catch them because lack of test cases. Updated the param construction logic and added test cases for it.

fix: update EndpointParams init call with test cases

---

.github/workflows/lint.yml
AWSClientRuntime/.swiftlint.yml
AWSClientRuntime/Sources/Auth/AWSCredentialsProvider.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderCachedConfig.swift
AWSClientRuntime/Sources/Auth/AWSCredentialsProviderChainDefaultConfig.swift
AWSClientRuntime/Sources/Config/Bundle.swift
AWSClientRuntime/Sources/Endpoints/ServiceEndpointMetadata.swift
AWSClientRuntime/Sources/Http/AWSUserAgentMetadata.swift
AWSClientRuntime/Sources/Protocols/RestJSON/RestJSONError.swift
AWSClientRuntime/Sources/Protocols/RestXML/RestXMLError.swift
AWSClientRuntime/Sources/Regions/DefaultRegionResolver.swift

- Specifies the config file when running the linter on CI
- Fixes infringing files

fix: Fixes issue where linter wasn’t using config file on CI

---

packageDependencies.plist

chore: update client runtime version to 0.8.0

---

Package.swift
packageDependencies.plist
scripts/generatePackageSwift.swift

Reverts version pinning to smithy and crt repos. 

chore: Reverts version pinning

---

Package.swift
packageDependencies.plist

Counterpart: https://github.com/awslabs/smithy-swift/pull/507

chore: bump aws-crt-swift to 0.5.4

---

Package.swift
Sources/Core/AWSClientRuntime/Auth/AWSCredentialsProvider.swift
packageDependencies.plist

Fixes #835 
Related https://github.com/awslabs/smithy-swift/pull/518

chore: bump aws-crt-swift to 0.5.6

---

Package.swift
packageDependencies.plist

chore: bump aws-crt-swift to 0.5.7

---

Package.swift
Sources/Core/AWSClientRuntime/Signing/AWSSignatureType.swift
packageDependencies.plist

chore: bump aws-crt-swift to 0.6.0

---

Package.swift
packageDependencies.plist

chore: bump smithy-swift to 0.6.1

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/PresignerGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AWSQueryOperationStackTest.kt

This PR updates codegen tests in response to https://github.com/awslabs/smithy-swift/pull/536
#923 

Fix: Updates tests in response to middleware changes

---

scripts/create-ec2-snapshot.sh
scripts/register-ec2-image.sh

This PR adds two scripts. One for creating an EC2 snapshot and the other for creating an EC2 AMI from the snapshot. 
These scripts require the user to modify them with their own values before running. 

chore: Adds scripts for creating EC2 snapshots and AMIs

---

scripts/register-ec2-image.sh

This PR adds an architecture option to the `register-ec2-image` script. 

chore: Adds architecture option to register-ec2-image script

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Commands/PrepareRelease.swift
AWSSDKSwiftCLI/Tests/AWSSDKSwiftCLITests/Commands/PrepareReleaseTests.swift

fix: Fixes file path to commit

---

Sources/Core/AWSClientRuntime/Auth/Credentials+CRT.swift
Sources/Core/AWSClientRuntime/Auth/Credentials.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider+CRT.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider+Factory.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProvider/CredentialsProvider.swift
Sources/Core/AWSClientRuntime/Config/Bundle.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/FileBasedConfiguration+CRT.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/FileBasedConfiguration.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/FileBasedConfigurationKeys.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/Store/FileBasedConfiguratioStore+CRT.swift
Sources/Core/AWSClientRuntime/FileBasedConfiguration/Store/FileBasedConfigurationStore.swift
Sources/Core/AWSClientRuntime/Regions/ProfileRegionProvider.swift
Sources/Core/AWSClientRuntime/Utils/Cache/FunctionCache.swift

Fixes outstanding warnings in SwiftLint.

chore: Fix SwiftLint issues

---

Package.swift
packageDependencies.plist

#981
Update `aws-crt-swift` to latest version (0.12.0).

chore: Update to aws-crt-swift 0.12.0

---

.github/workflows/codegen-build-test-on-comment.yml

This PR creates a duplicate of the codegen-build-test workflow that can be triggered on a PR via a comment containing `/test`
#977 

chore: Creates codege-build-test-on-comment workflow

---

.github/workflows/codegen-build-test-on-comment.yml

fix: Typo in codegen-build-test workflow

---

.github/workflows/codegen-build-test-on-comment.yml

chore: Log SHA & head ref for comment-initiated workflow

---

.github/workflows/codegen-build-test-on-comment.yml

chore: Use Github XL runner for codegen-build-test

---

.github/workflows/lint.yml

Updates SwiftLint version used to latest available.

chore: Update swiftlint to 0.52.3

---

Sources/Core/AWSClientRuntime/Auth/CredentialsProvidingCRTAdapter.swift

Fixes one Swiftlint issue raised after updating Swiftlint to latest.

chore: Fix Swiftlint issue

---

AWSSDKSwiftCLI/Sources/AWSSDKSwiftCLI/Resources/Package.Base.swift
Package.swift
Sources/Core/AWSClientRuntime/Auth/CredentialsProviders/ECSCredentialsProvider.swift

- Update Package.swift to include changes that were added to codegen
- Add AWSSTS as ECS integration test dependency

fix: Update Package.swift based on codegen and add AWSSTS as ECS integration test dependency

---

Sources/Core/AWSClientRuntime/UserAgent/OSMetadata.swift
Tests/Core/AWSClientRuntimeTests/UserAgent/OSMetadataTests.swift

feat: add visionOS support to useragent

---

Package.swift
packageDependencies.plist

#1154
Updates to aws-crt-swift 0.15.0 to get the latest fixes on CRT libraries.

chore: Update to aws-crt-swift 0.15.0

---

.github/workflows/lint.yml

- Use latest Swiftlint (0.53.0)
- Workflow file cleanup

chore: Update swiftlint to 0.53.0

---

IntegrationTests/Services/AWSSQSIntegrationTests/SQSTests.swift
Sources/Services/AWSSQS/SQSClient.swift
Sources/Services/AWSSQS/SQSClientProtocol.swift
Sources/Services/AWSSQS/models/Models.swift
codegen/sdk-codegen/aws-models/sqs.2012-11-05.json

Update models for SQS and add an integration test
#763 
- Update SQS models which now use AWS Json instead of AWS Query. The rest of the model update will occur during the next release.
- Add an integration test to ensure that it works.

feat: update SQS to latest model that uses aws json protocol + add integration test

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/EventStreamTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AWSQueryOperationStackTest.kt

#730
Fixes tests related to doc comment change in https://github.com/smithy-lang/smithy-swift/pull/621.

fix: Fix tests related to operation doc header

---

.github/workflows/generate-documentation.yml

#730
Fix bug in workflow inline script

fix: Fix script for extracting version from GH ref

---

Package.swift
packageDependencies.plist

chore: Update to aws-crt-swift 0.20.0

---

IntegrationTests/Services/AWSS3IntegrationTests/S3ErrorIn200Test.swift
Package.swift
Sources/Core/AWSClientRuntime/Middlewares/Sha256TreeHashMiddleware.swift
Tests/Core/AWSClientRuntimeTests/Sigv4/SigV4SigningTests.swift
packageDependencies.plist

chore: update to CRT 0.22.0

---

Package.swift
packageDependencies.plist

Update to latest published smithy-swift version

chore: Update smithy-swift to 0.38.0

---

gradle.properties

#1332
Update to use Smithy 1.44.0 (latest release).

chore: Update to Smithy 1.44.0

---

.github/workflows/lint.yml

#1341
Update Swiftlint from 0.53.0 to 0.54.0

chore: Update swiftlint to 0.54.0

---

Sources/Core/AWSClientRuntime/Protocols/Ec2Query/Ec2Response.swift

Link to customer-raised discussion: https://github.com/awslabs/aws-sdk-swift/discussions/1354

fix: Remove @testable from production code.

---

.github/workflows/codegen-build-test.yml
.github/workflows/release-configuration-build.yml

https://github.com/awslabs/aws-sdk-swift/issues/1357

chore: Add build with release configuration to Github CI

---

IntegrationTests/Services/AWSS3IntegrationTests/S3EmptyBody404Tests.swift
Sources/Core/AWSClientRuntime/Middlewares/Sha256TreeHashMiddleware.swift
codegen/protocol-test-codegen-local/Tests/swift-codegen/WaitersTests/WaiterModels+Equatable.swift
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/S3ExpiresTest.kt

https://github.com/awslabs/aws-sdk-swift/issues/898
**Companion PR: https://github.com/smithy-lang/smithy-swift/pull/700**
*All the actual work is done in companion PR above.
Updates codegen tests affected by removed `Equatable` protocol conformance in companion PR.

feat!: Remove Equatable protocol conformance unless necessary

---

.github/workflows/codegen-build-test.yml
.github/workflows/continuous-integration.yml
.github/workflows/integration-test.yml
Package.swift
packageDependencies.plist

For testing of branch https://github.com/smithy-lang/smithy-swift/pull/718

fix: Bring in latest URLSessionHTTPClient from main branch

---

Sources/Services/AWSAPIGateway/models/Models.swift
Sources/Services/AWSApiGatewayV2/models/Models.swift
Sources/Services/AWSAppConfig/models/Models.swift
Sources/Services/AWSAppConfigData/models/Models.swift
Sources/Services/AWSAppSync/models/Models.swift
Sources/Services/AWSBedrockRuntime/models/Models.swift
Sources/Services/AWSCloudFront/models/Models.swift
Sources/Services/AWSCodeGuruProfiler/models/Models.swift
Sources/Services/AWSDataExchange/models/Models.swift
Sources/Services/AWSIoTDataPlane/models/Models.swift
Sources/Services/AWSIoTWireless/models/Models.swift
Sources/Services/AWSLambda/models/Models.swift
Sources/Services/AWSLocation/models/Models.swift
Sources/Services/AWSNeptunedata/models/Models.swift
Sources/Services/AWSS3/models/Models.swift
Sources/Services/AWSSageMakerRuntime/models/Models.swift
Sources/Services/AWSSchemas/models/Models.swift
Sources/Services/AWSTnb/models/Models.swift

Update codegen after the merge of https://github.com/smithy-lang/smithy-swift/pull/723

chore: Updated codegen

---

Package.swift

chore: Uncomment service targets

---

Sources/Services/AWSCloudFrontKeyValueStore/Sources/AWSCloudFrontKeyValueStore/CloudFrontKeyValueStoreClient.swift
Sources/Services/AWSEC2/Sources/AWSEC2/EC2Client.swift
Sources/Services/AWSECS/Sources/AWSECS/ECSClient.swift
Sources/Services/AWSEventBridge/Sources/AWSEventBridge/EventBridgeClient.swift
Sources/Services/AWSKinesis/Sources/AWSKinesis/KinesisClient.swift
Sources/Services/AWSMediaConvert/Sources/AWSMediaConvert/MediaConvertClient.swift
Sources/Services/AWSRoute53/Sources/AWSRoute53/Route53Client.swift
Sources/Services/AWSS3/Sources/AWSS3/Models.swift
Sources/Services/AWSS3/Sources/AWSS3/S3Client.swift
Sources/Services/AWSS3/Tests/AWSS3Tests/DeleteObjectTaggingRequestTest.swift
Sources/Services/AWSS3/Tests/AWSS3Tests/GetObjectRequestTest.swift
Sources/Services/AWSSQS/Sources/AWSSQS/SQSClient.swift
Sources/Services/AWSTranscribeStreaming/Sources/AWSTranscribeStreaming/TranscribeStreamingClient.swift

Regenerates code after merging metrics

chore: Update generated code

---

Sources/Core/AWSSDKHTTPAuth/Tests/AWSSDKHTTPAuthTests/SigV4AuthSchemeTests.swift

Companion PR: https://github.com/smithy-lang/smithy-swift/pull/787

chore: Add SigV4 things to smithy-swift

---

.github/workflows/generate-documentation.yml

fix: Delete unnecessary backward slashes from GH DocC workflow

---

.github/workflows/generate-documentation.yml

- https://github.com/awslabs/aws-sdk-swift/issues/1651

fix: DocC workflow

---

sdk.properties

chore: Remove AWS CodeStar service.

---

sdk.properties

chore: Remove straggling codestar stuff

---

.github/dependabot.yml

- https://github.com/awslabs/aws-sdk-swift/issues/1711

chore: Make dependabot run daily

---

codegen/sdk-codegen/aws-models/s3.json

fix: Pull in Smithy-only S3 model change

---

IntegrationTests/Services/AWSSTSIntegrationTests/STSWebIdentityAWSCredentialIdentityResolverTests.swift

Disables this test while we improve the configuration of the associated role.

chore: Disable STSWebIdentityAWSCredentialIdentityResolverTest

---

Package.swift
packageDependencies.plist

Updates `aws-crt-swift` to latest version (0.42.0).

chore: Update to aws-crt-swift 0.42.0

---

codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/customizations/S3ExpiresTest.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/ec2query/Ec2QueryHttpResponseBindingErrorGeneratorTests.kt
codegen/smithy-aws-swift-codegen/src/test/kotlin/software/amazon/smithy/aws/swift/codegen/restxml/AWSRestXMLHTTPResponseBindingErrorGeneratorTests.kt

Solely contains codegen test fixes related to the codegen format changes in https://github.com/smithy-lang/smithy-swift/pull/894.

chore: Proper formatting of generated structures

---

Package.swift
packageDependencies.plist

chore: bump crt version to 0.47.0

---

PerformanceTests/Package.swift

feat: add executable as product

---

Package.swift
Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/AWSClientConfigDefaultsProvider.swift
Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/Middlewares/AmzSdkRequestMiddleware.swift
Sources/Core/AWSClientRuntime/Sources/AWSClientRuntime/Retry/AWSRetryConfig.swift
Sources/Core/AWSSDKEventStreamsAuth/Sources/AWSSSDKEventStreamsAuth/Context+Signing.swift
Sources/Core/AWSSDKEventStreamsAuth/Tests/AWSSDKEventStreamsAuthTests/SigV4EventSigningTests.swift
Sources/Core/AWSSDKHTTPAuth/Sources/AWSSDKHTTPAuth/AWSSigV4Signer.swift
Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentityResolvers/DefaultAWSCredentialIdentityResolverChain.swift

- Remove unneeded dependencies from `AWSClientRuntime`
- Remove unused imports
- Remove references to `ClientRuntime` re-export & extension of Foundation type

chore!: Runtime module cleanup

---

gradle.properties

chore: bump to smithy 1.62
